### ISSUE TITLE
HarfBuzz 3.0.0 tracker issue

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3078]
With the subsetter library approaching API/ABI stability I think we should transition to HB 3.x. Here's a tracker for what needs fixing before that release. Mainly it is just:

  - [x] https://github.com/harfbuzz/harfbuzz/issues/3012
    - [x] Final check of the .so to make sure exposed symbols are all good and intended. https://github.com/harfbuzz/harfbuzz/issues/3130
    - [ ] Ideally, a "getting started" section to the subset library; maybe exists already.
    - [ ] Proper release notes.
    - [ ] autoconf/meson options to disable building it? Perhaps not.

 

But a couple small issues as well:

  - [x] https://github.com/harfbuzz/harfbuzz/pull/3076

  - [x] https://github.com/harfbuzz/harfbuzz/issues/3077

  - [ ] This oss-fuzz issue:
     https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36236

     I think I introduced it in https://github.com/harfbuzz/harfbuzz/pull/3027 so I want to fix before a release.

Would be nice to fix, but definitely no release-blocker:

  - [x] https://github.com/harfbuzz/harfbuzz/issues/3069
  - [ ] https://github.com/harfbuzz/harfbuzz/issues/3074

**Comment by behdad** [comment]
Ideally also:
  - [ ] https://github.com/harfbuzz/harfbuzz/issues/3002
  - [ ] https://github.com/harfbuzz/harfbuzz/issues/3109
  - [ ] https://github.com/harfbuzz/harfbuzz/issues/3038
  - [ ] https://github.com/harfbuzz/harfbuzz/issues/2455

**Comment by stha09** [comment]
Is it possible to get a release soon? Latest Chromium Dev update already depends on unreleased harfbuzz features.

**Comment by behdad** [comment]
We can make a release today, call it 2.9.0. There's still API changes I like to make so we're not at 3.0.0 mark yet.

@khaledhosny can you roll a release please?

**Comment by khaledhosny** [comment]
Should I list the changes to subset API in the NEWS file, so far we never listed any subset API there.

**Comment by khaledhosny** [comment]
Also, I don’t like the fact we are going to break the subset API twice in a short period of time (even with being unstable and all), we should change it once for good. Chromioum depending on an unreleased HarfBuzz looks like something that should be fixed there.

**Comment by behdad** [comment]
> Should I list the changes to subset API in the NEWS file, so far we never listed any subset API there.

Mention them briefly, and point to this issue / opening new issues for API/other feedback. Thanks!

**Comment by behdad** [comment]
> Also, I don’t like the fact we are going to break the subset API twice in a short period of time (even with being unstable and all), we should change it once for good.

I have similar feelings. Okay let's think about it, make up our (my :))) mind and release with the final API.

Let's wait till Monday.

> Chromioum depending on an unreleased HarfBuzz looks like something that should be fixed there.

**Comment by stha09** [comment]
Chromium bundles harfbuzz, but most Linux distributions don't like bundled libraries. A release on Monday works for me. Thanks guys.

**Comment by behdad** [comment]
Let's do this: put back the old API in (internally just calling the new API), and make a 2.9.0 release.

We then add all new API we like and make 2.9.x releases. Only when we're fully satisfied with the new API, we'll remove the old and call it 3.0.0.

**Comment by behdad** [comment]
> Let's do this: put back the old API in (internally just calling the new API), and make a 2.9.0 release.

The first part is done. @khaledhosny can we get a release please?

**Comment by khaledhosny** [comment]
> The first part is done. @khaledhosny can we get a release please?

Done.

**Comment by khaledhosny** [comment]
@alerque I tagged a released but GitHub release was not created, can you take a look? I probably broke something in the CI setup.

**Comment by alerque** [comment]
Yes looking.

**Comment by alerque** [comment]
Found it @khaledhosny, the culprit was d203267e5. I understand why it *looked* like that wasn't doing anything, but actually it was covering up an illogical quirk in Circle CI. I have a PR incoming to fix it back up with a little more documentation this time so others aren't tempted to make the same mistake.

**Comment by behdad** [comment]
There's no blockers left. Let's get 2.9.1 out (https://github.com/harfbuzz/harfbuzz/issues/3183), switch Skia / Chrome to new API, let it sit a couple weeks, if all good, then remove old API and call it 3.0.0. @garretrieger

**Comment by behdad** [comment]
> There's no blockers left. Let's get 2.9.1 out (#3183), switch Skia / Chrome to new API, let it sit a couple weeks, if all good, then remove old API and call it 3.0.0. @garretrieger

2.9.1 was released a week ago. @garretrieger have you had a chance to roll Skia to new API yet?

**Comment by garretrieger** [comment]
Yes, Skia is ready for the new harfbuzz api: https://skia-review.googlesource.com/c/skia/+/437121

Ben added feature detection that switches to the new methods if they are present.

**Comment by khaledhosny** [comment]
3.0.0 was just released.

**Comment by behdad** [comment]
woohoo! Thanks @khaledhosny and others!
