### ISSUE TITLE
hb-info left TODO items.

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4049]
- [x] Add `--list-scripts` and separate that part from `--list-features`.
- [x] Add `--script` and `--language` and if those are specified
- [x]  Make `--list-features` respect `--script` and `--language`.
- [x] Add `--direction` that affects `--extents`.
- [x] Add `--ot-script` and `--ot-language`...
- [x] Make `--list-scripts` list both OT tags and ISO/BCP.
- [x] Add `--show-glyph-count`.
- [x] Add `--show-unicode-count`.
- [x] Add `--show-upem`.
- [x] Add `--show-extents`.
- [x] Add `--list-names`.
- [x] Add `--show-family`, `--show-style`, `--show-full-name`, `--show-postscript-name`, `--show-version`.
- [x] Add `--dump-table`.
- [x] Add `--get-metric`.
- [x] Add `--get-baseline`?
- [x] Color and outline information.
- [x] Shaping technology information.
- [ ] Add something for `cvXX` info? Rare.
- [ ] _Add `--show-optical-size`?_ Maybe not. Rare and deprecated...
- [ ] _Add `--show-num-faces`._ Maybe not. Complicated to add.

_Originally posted by @behdad in https://github.com/harfbuzz/harfbuzz/issues/4048#issuecomment-1397532219_

**Comment by davelab6** [comment]
@MariannaPaszkowska @chrissimpkins @simoncozens any requests?

**Comment by khaledhosny** [comment]
`--list-scripts` does not show an ISO tag for DFLT script (I guess it is an empty string?)
```
Layout script information:

Table: GSUB
	Script:  (DFLT)
	Script: Arab (arab)
		Language: ar (ARA )
		Language: ks (KSH )
		Language: ms (MLY )
		Language: sd (SND )
		Language: ur (URD )
	Script: Latn (latn)
		Language: tr (TRK )
```

Also, should `defaultLangSys` be represented in some way? (since it can be NULL, it would be nice to know if it is present or not).

**Comment by simoncozens** [comment]
That is quite lovely. Only thing I would ask for is JSON output. :-) (Or something self-describing and parsable, anyway.)

**Comment by behdad** [comment]
> `--list-scripts` does not show an ISO tag for DFLT script (I guess it is an empty string?)

I'm using HB_SCRIPT_COMMON (Zyyy) now.

**Comment by behdad** [comment]
> That is quite lovely. Only thing I would ask for is JSON output. :-) (Or something self-describing and parsable, anyway.)

JSON is planned for the future (probably when you get to do it :))). For now, `-q` generates machine-readable output.

**Comment by behdad** [comment]
cc @twardoch for requests.

**Comment by khaledhosny** [comment]
`--show-glyph=gid` (draws glyph like hb-draw), and/or `--show-glyph-path` (show textual path, either SVG or CharString-like )?

**Comment by khaledhosny** [comment]
Possibly taking name instead of gid (and allowing gidNNNN).

**Comment by behdad** [comment]
> `--show-glyph=gid` (draws glyph like hb-draw), and/or `--show-glyph-path` (show textual path, either SVG or CharString-like)?

Yeah so far I tried to avoid per-character/glyph info. Most of that can be output from hb-shape/view.

**Comment by behdad** [comment]
Did most of these. Closing for now, but keep ideas coming and I'll see.
