### ISSUE TITLE
Improving CMake and its tests

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#678]
First run CMake like this:

```
cmake -DHB_CHECK=ON -Bbuild -H. -GNinja && ninja -Cbuild && ninja -Cbuild test
```

<s>As #675 turned out, CMake, or its testing need improvements from various aspects:</s> almost done

* [x] Exact path for working directory of first test should be fixed in a portable way, `${PROJECT_BINARY_DIR}/CMakeFiles/harfbuzz.dir/src` should be replaced with some CMake magic (Improved but no much luck as https://stackoverflow.com/q/48296061)
* [x] `check-defs.sh` has some `make` stuff in inside that should be corrected before enabling it (#710)
* [x] `check-libstdc++.sh` is not happening on macOS at least it seems? (almost done on #707)
* [x] `check-static-inits.sh` is failing as it says there are objects with static initialization (not on Apple, but it is fine I guess)
* [x] After fixing the tests, some ci bot (or all of them) should test cmake build with `-DBUILD_SHARED_LIBS=ON`, https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml
* [x] As `check-symbols.sh` there are private symbols exposed on CMake build? (fixed on #705, but maybe there are some better ways?)
* [x] `check-c-linkage-decls.sh` and `check-header-guards.sh` are not working, are they autotools specific?

Remained ones, for future:
* porting some of test scripts on src/ to python so we can run them on Visual C++ builds also (and test hb_check on appveyor, use `objdump` instead `nm` on Windows?)
* Autotools builds whole harfbuzz again on building hb-fuzzer, https://github.com/harfbuzz/harfbuzz/blob/master/test/fuzzing/Makefile.am but our cmake's `hb-fuzzer` is not doing the same. <s>Why autotools does that on building hb-fuzzer?</s> (update: explained by behdad below, done but commented: https://github.com/harfbuzz/harfbuzz/blob/master/test/fuzzing/CMakeLists.txt#L9)

**Comment by behdad** [comment]
> As check-symbols.sh there are private symbols exposed on CMake build?

That's weird. `HB_INTERNAL` is supposed to take care of those.

>     check-static-inits.sh is failing as it says there are objects with static initialization

Yeah not sure this works on Apple platforms.

>     check-defs.sh has some make stuff in inside that should be corrected before enabling it

Right. It just makes sure harfbuzz.def is built.

>     check-libstdc++.sh is not happening on macOS at least it seems?

Yeah I think on Mac we always get linked to it.

>     check-c-linkage-decls.sh and check-header-guards.sh are not working, are they autotools specific?

They need HBSOURCES and HBHEADERS defined. But they try to find those if they are not defined. There was a bug in check-c-linkage-decls.sh. Just fixed. Try again?

>     After fixing the test, some ci bot (or all of them) should test cmake build with -DBUILD_SHARED_LIBS=ON,

Why is BUILD_SHARED_LIBS not the default BTW?

>     Autotools builds whole harfbuzz again on building hb-fuzzer, https://github.com/harfbuzz/harfbuzz/blob/master/test/fuzzing/Makefile.am but our cmake's hb-fuzzer is not doing the same. Why autotools does that on building hb-fuzzer?

Because we build a special version of the library with different parameters to better test out-of-memory codepaths:
```
FUZZING_CPPFLAGS= \
        -DHB_NDEBUG \
        -DHB_MAX_NESTING_LEVEL=3 \
        -DHB_SANITIZE_MAX_EDITS=3 \
        -DHB_BUFFER_MAX_LEN_FACTOR=3 \
        -DHB_BUFFER_MAX_LEN_MIN=8 \
        -DHB_BUFFER_MAX_LEN_DEFAULT=128 \
        -DHB_BUFFER_MAX_OPS_FACTOR=8 \
        -DHB_BUFFER_MAX_OPS_MIN=64 \
        -DHB_BUFFER_MAX_OPS_DEFAULT=1024 \
        $(NULL)
EXTRA_LTLIBRARIES = libharfbuzz-fuzzing.la
libharfbuzz_fuzzing_la_LINK = $(libharfbuzz_la_LINK)
libharfbuzz_fuzzing_la_SOURCES = $(libharfbuzz_la_SOURCES)
libharfbuzz_fuzzing_la_CPPFLAGS = $(libharfbuzz_la_CPPFLAGS) $(FUZZING_CPPFLAGS)
```

**Comment by ebraminio** [comment]
Very helpful, thank you.

> Why is BUILD_SHARED_LIBS not the default BTW?

It is advised to not set them and let users to choose between them, not sure if setting default behavior is possible.

**Comment by ebraminio** [comment]
Just one of them now fails, `Ouch, header file ./hb-gobject-structs.h does not have correct preprocessor guards`  is anything wrong with hb-gobject-structs.h do you guess?

**Comment by ebraminio** [comment]
> Because we build a special version of the library with different parameters to better test out-of-memory codepaths: [...]

Hmmm, so I should get some separate flag to enabling testing on cmake to know whether we want to build hb-fuzzer beforehand with such flags.

**Comment by behdad** [comment]
A couple things:
- Can you make "ninja check" also work?
- "ninja test" doesn't rebuild the library by default. Is that a common CMake idiom? I like the make idiom that check builds library first.

**Comment by ebraminio** [comment]
> Can you make "ninja check" also work?

Searched couple of minutes with no success.

> "ninja test" doesn't rebuild the library by default. Is that a common CMake idiom? I like the make idiom that check builds library first.

Hmm, interesting I don't know about that but I believe it is better to have `ninja -Cbuild` along with `ninja -Cbuild test` anyway, and as configuring the whole project is also cheap, if I were, I was using these two similar command and put them on bashrc/zshrc as aliases,

Just to know if whole tests are fine I suggest using this command all of the time, no matter the level of changes:
```bash
cmake -DHB_CHECK=ON -Bbuild -H. -GNinja && ninja -Cbuild && CTEST_PARALLEL_LEVEL=8 ninja -Cbuild test
```
setting an alias like `alias qc="..."` (quick check) would be cool I guess :)

To know exactly which test is failed and print its output
```bash
cmake -DHB_CHECK=ON -Bbuild -H. -GNinja && ninja -Cbuild && CTEST_OUTPUT_ON_FAILURE=1 ninja -Cbuild test
```
and one alias like `alias dc="..."` (detailed check) for this one :)

The combination also would work also :)

Some extra notes to mention,

The reason about above distinction is when you run tests in parallel, you will not see failure in correct order thus the print might be confusing, but parallel builds are faster and in rapid develop/test cycles they can be run on every file saving, thus making sure you small change didn't broke anything.

`ninja -Cbuild test`, unlike the ninja build command, is just a wrapper around internal `ctest` binary thus it doesn't get optimal number of parallel testing.

Also `cmake --build build` and `cmake --build build --target test` can be used instead `ninja -Cbuild` and `ninja -Cbuild test` so no matter underlying generator and compiler, ninja or unix make or msvc, same command will work for compilation and testing.

**Comment by ebraminio** [comment]
Right :) I really tried to combine those two in one with no success that I was thinking about some developer specific script inside the repo with features like installing needed packages on a new system and being usable also in CI bots.

**Comment by behdad** [comment]
With master, check-header-guards.sh is failing for me with ninja but not make.

**Comment by ebraminio** [comment]
Hmmm, what error it give? They are limited to distribution folder https://github.com/harfbuzz/harfbuzz/blob/master/CMakeLists.txt#L759 (now I think if that was really needed?) and are working on CI https://circleci.com/gh/harfbuzz/harfbuzz/2808 but I guess something is wrong, perhaps our logic of detecting whether cmake is in distribution folder https://github.com/harfbuzz/harfbuzz/blob/master/CMakeLists.txt#L108-L113 is broken somehow.

**Comment by ebraminio** [comment]
As #710 and others, this is almost done so lets close it :)
