### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#830]
Tracking high-level roadmap:

July 2018, HarfBuzz 2.0:
- [ ] AAT morx/kerx/trak shaping.
- [ ] TrueType-flavored glyph subsetting.

July 2019, HarfBuzz 3.0:
- [ ] Completely move Chromium off sfntly.
- [ ] CFF / CFF2 subsetting.
- [ ] TrueType varfont subsetting.
- [ ] Varfont instantiation.

July 2020, HarfBuzz 4.0:
- [ ] Completely move Google Fonts off fonttools.
- [ ] Graphite or pieces thereof (Nastaliq...)
- [ ] Autohinting / rasterization.

**Comment by ebraminio** [comment]
I guess [GitHub project](https://github.com/harfbuzz/harfbuzz/projects) also can be used.

Lets list things here (feel free to edit this post) that may or may not on the table but if a ABI/API breakage is planned, consider all of them for the redesign:
* Kashida, #586 and more, [GetJustificationOpportunities](https://github.com/harfbuzz/harfbuzz/blob/21646cc4a6160088933774e179df9be4865a9f4b/src/hb-directwrite.cc#L739), [hb_directwrite_shape_experimental_width](https://github.com/harfbuzz/harfbuzz/blob/21646cc4a6160088933774e179df9be4865a9f4b/src/hb-directwrite.cc#L916)
* Providing useful things for Wine project to replicate DirectWrite API and separation of substitution/positioning, [GetGlyphs](https://github.com/harfbuzz/harfbuzz/blob/21646cc4a6160088933774e179df9be4865a9f4b/src/hb-directwrite.cc#L672) [GetGlyphPlacements](https://github.com/harfbuzz/harfbuzz/blob/21646cc4a6160088933774e179df9be4865a9f4b/src/hb-directwrite.cc#L717), [1](https://lists.freedesktop.org/archives/harfbuzz/2015-August/005007.html) [2](https://lists.freedesktop.org/archives/harfbuzz/2015-July/004950.html)
* Providing Thread context, #497

**Comment by behdad** [comment]
> Providing useful things for Wine project being able [at least theoretically] to replicate DirectWrite/Uniscribe API and the separation of substitution/positioning, GetGlyphs GetGlyphPlacements, 1 2

I'll reply to your mailing list thread about it: https://lists.freedesktop.org/archives/harfbuzz/2018-February/006445.html

> Providing Thread context, #497

Nothing to be done there. I'll leave a comment on that issue.

**Comment by davelab6** [comment]
What does " Graphite or pieces thereof (Nastaliq...)" mean? :)

**Comment by behdad** [comment]
> What does " Graphite or pieces thereof (Nastaliq...)" mean? :)

Implement, natively, parts of Graphite that make sense. To be determined what that actually means. :)

**Comment by davelab6** [comment]
Apart from SIL, is anyone making Graphite fonts in 2018?

**Comment by khaledhosny** [comment]
> Apart from SIL, is anyone making Graphite fonts in 2018?

This isn’t about supporting Graphite in HarfBuzz (we already have that), but burrowing some ideas from Graphite to be used in OpenType fonts, like the collision detection for Nastaliq (which can be useful for other style or scripts as well).

**Comment by davelab6** [comment]
Ah okay cool; Behdad has been saying that GPOS/GSUB is more powerful than the current widespread understanding and I'm fully in favor of demos of that :)

>  Autohinting / rasterization.

What does this mean? :)

**Comment by ebraminio** [comment]
> rasterization

Maybe the return of [glyphy](https://github.com/behdad/glyphy) using features available that days!

**Comment by behdad** [comment]
> What does this mean? :)

Exactly what you read ;).

**Comment by rsheeter** [comment]
Autohinting in advance ala ttfautohint or at runtime (so we don't have to
deliver the hints)?

**Comment by behdad** [comment]
> Autohinting in advance ala ttfautohint or at runtime (so we don't have to deliver the hints)?

Runtime. Minimal autohinting, ala OS X, which when combined with possible rasterization, would allow a full text rendering stack without FreeType.

**Comment by ebraminio** [comment]
Now that harfbuzz provides sanitization and plans for rasterization/auto-hinting, I think a public font sanitization (OTS like) and serialization (fonttools/TTX like) also can be considered for the roadmap.

**Comment by khaledhosny** [comment]
Yes, I was wondering about that too. May be it will finally be possible to use HarfBuzz in OTS to do proper sensitization of layout tables (though not sure how useful it would be given that OTS’s two users use HarfBuzz for shaping anyway).

**Comment by behdad** [comment]
HarfBuzz won't ever be a lint the way ots-sanitize is being used. It might, however, become a replacement of ots to "subset" fonts before passing them onto the OS.

**Comment by ebraminio** [comment]
I wonder what it take to provide enough API to port glyphy to harfbuzz, just like https://github.com/behdad/glyphy/pull/12 that was porting glyphy to Win32 API and like FT_GlyphSlot::glyph.outline.points https://github.com/ebraminio/glcourse/blob/master/hbftsvg.cc#L75-L81

**Comment by behdad** [comment]
> I wonder what it take to provide enough API to port glyphy to harfbuzz, just like behdad/glyphy#12 that was porting glyphy to Win32 API and like FT_GlyphSlot::glyph.outline.points https://github.com/ebraminio/glcourse/blob/master/hbftsvg.cc#L75-L81

Right. Getting glyph outline. That needs to be implemented in glyf table (maybe something for you in a couple of months when the current work is all cleaned up and working) and later CFF.

**Comment by ebraminio** [comment]
> (maybe something for you in a couple of months when the current work is all cleaned up and working)

I couldn't wait that much so prepared a working draft for it https://github.com/harfbuzz/harfbuzz/compare/master...ebraminio:glyf :)

**Comment by behdad** [comment]
> I couldn't wait that much so prepared a working draft for it master...ebraminio:glyf :)

Phew. Just finish one first!!!

Or take CFF.

**Comment by ebraminio** [comment]
Hehehe, there is an interesting implementation https://github.com/nodebox/opentype.js/blob/master/src/tables/cff.js btw putting its link here hopefully for future use

**Comment by KrasnayaPloshchad** [comment]
CFF2 varfont subsetting should be fixed at the same stage when HarfBuzz 3.0 released.

**Comment by ebraminio** [comment]
I think we can close this in favor of https://github.com/harfbuzz/harfbuzz/projects

**Comment by behdad** [comment]
Cool. Thanks Ebrahim! I should find a way to subscribe to those.
